# Question to be solved

1. Array Creation
Create a 3x3 NumPy array with values ranging from 1 to 9. Then, reshape it into a 1D array.
2. Array Indexing & Slicing
Create a 5x5 matrix of integers ranging from 1 to 25. Extract a 3x3 submatrix from the center.
3. Element-wise Operations
Given two arrays A = np.array([1, 2, 3, 4]) and B = np.array([10, 20, 30, 40]), perform element-wise addition, multiplication, and division.
4. Broadcasting
Create a 4x4 matrix with all values as 1. Multiply it by a 1D array np.array([1, 2, 3, 4]) using broadcasting.
5. Statistical Operations
Generate a 1D array of 100 random numbers from a normal distribution. Find the mean, median, standard deviation, and variance of the array.
6. Boolean Masking
Create an array of integers from 1 to 20. Use boolean masking to extract all even numbers from the array.
7. Array Manipulation
Create a 1D array of numbers from 1 to 10. Insert the number 99 at index 5 and then delete the element at index 3.
8. Matrix Operations
Create two 3x3 matrices and compute their matrix multiplication using the @ operator and np.dot() function.
9. Aggregations
Create a 5x5 matrix filled with random values. Compute the sum of all elements, the sum of each row, and the sum of each column.
10. Linear Algebra
Create a 3x3 matrix and compute its inverse, determinant, and eigenvalues using NumPy’s linear algebra functions.

# Answers

## 1

In [1]:
import numpy as np

In [19]:
a = np.random.randint(1,9,size=(3,3))
a

array([[7, 8, 7],
       [4, 7, 8],
       [2, 2, 7]])

In [20]:
a.reshape(1,9)

array([[7, 8, 7, 4, 7, 8, 2, 2, 7]])

## 2

In [22]:
a = np.random.randint(1,25,size=(5,5))
a

array([[23, 22, 24,  8,  9],
       [14, 11, 19, 15,  9],
       [ 7, 14, 13, 23, 16],
       [11, 10, 16, 23,  5],
       [21, 11,  4, 21, 18]])

In [27]:
b = a[1:4,1:4]
b

array([[11, 19, 15],
       [14, 13, 23],
       [10, 16, 23]])

In [28]:
b.shape

(3, 3)

## 3

In [29]:
a= np.array([1,2,3,4])
b= np.array([10,20,30,40])

In [30]:
a+b

array([11, 22, 33, 44])

In [31]:
a-b

array([ -9, -18, -27, -36])

In [32]:
a*b

array([ 10,  40,  90, 160])

## 4

In [37]:
a = np.ones([4,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
b = np.array([1, 2, 3, 4])

In [44]:
c = np.broadcast_to(b, (4,4))
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [45]:
c*a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## 5

In [49]:
a= np.random.randint(100,size=(1,100))
a

array([[59, 39, 98, 25, 38, 39, 52, 92, 53, 84, 75, 12, 40, 34, 38, 84,
        56, 93, 26, 44, 87, 62, 86, 43, 87,  1, 16,  9, 96, 69,  5, 35,
         2, 38, 97, 77, 16, 42, 67, 98, 26, 62,  1, 34, 22, 12, 12, 68,
        67, 99, 98, 94, 79, 45, 92, 68, 45, 30, 19, 99, 56, 44, 12, 53,
        95, 29, 60, 83,  0, 95, 72, 46, 69, 10, 68, 95, 60,  7, 94,  4,
        44, 73, 89,  5, 99, 43,  4, 41, 42, 43, 68, 92, 25, 53, 86, 27,
        87, 70, 14, 58]])

In [50]:
a.shape

(1, 100)

In [51]:
np.mean(a)

53.01

In [52]:
np.median(a)

53.0

In [54]:
np.std(a)

30.51933649344297

In [55]:
np.var(a)

931.4298999999999

## 6

In [56]:
a = np.random.randint(1,20,size=(1,20))
a

array([[14, 12,  8,  2,  4,  8,  4, 15,  3, 10,  7, 15,  7,  3,  6, 17,
        15, 10,  3,  4]])

In [58]:
a[a%2==0]

array([14, 12,  8,  2,  4,  8,  4, 10,  6, 10,  4])

## 7

In [62]:
a = np.random.randint(10,size=(1,10))
a

array([[6, 9, 3, 5, 3, 4, 1, 9, 8, 8]])

In [65]:
a[0,5]=99
a

array([[ 6,  9,  3,  5,  3, 99,  1,  9,  8,  8]])

In [67]:
np.delete(a,3)

array([ 6,  9,  3,  3, 99,  1,  9,  8,  8])

## 8

In [71]:
a=np.random.randint(100,size=(3,3))
a
b = np.random.randint(100,size=(3,3))
b

array([[22, 51, 59],
       [64,  4, 41],
       [86, 53, 40]])

In [72]:
a@b

array([[10450,  5061,  7541],
       [ 4296,  2452,  4728],
       [ 9076,  4394,  7997]])

In [73]:
np.dot(a,b)

array([[10450,  5061,  7541],
       [ 4296,  2452,  4728],
       [ 9076,  4394,  7997]])

## 9

In [74]:
a = np.random.randint(10,size=(5,5))
a

array([[4, 5, 9, 4, 6],
       [8, 3, 7, 8, 7],
       [4, 9, 9, 3, 7],
       [2, 0, 7, 1, 5],
       [4, 3, 9, 9, 3]])

In [77]:
a.sum()

136

In [76]:
a.sum(axis=0)

array([22, 20, 41, 25, 28])

In [78]:
a.sum(axis=1)

array([28, 33, 32, 15, 28])

## 10

In [79]:
a = np.random.randint(10,size=(3,3))
a

array([[9, 2, 2],
       [8, 7, 2],
       [1, 8, 8]])

In [82]:
np.linalg.det(a)

350.00000000000017

In [84]:
np.linalg.eigvals(a)

array([15.17291884+0.j        ,  4.41354058+1.89422109j,
        4.41354058-1.89422109j])

In [85]:
np.linalg.inv(a)

array([[ 1.14285714e-01, -6.16790569e-18, -2.85714286e-02],
       [-1.77142857e-01,  2.00000000e-01, -5.71428571e-03],
       [ 1.62857143e-01, -2.00000000e-01,  1.34285714e-01]])

inverse(A) = adj(A)/det(A)